title: Feras Dayoub
description: Feras Dayoub's Home Page
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day

remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
